---
title: "Pathway Analysis"
author: "Jasmine Chong, Jeff Xia"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Pathway Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## 1. Introduction

The pathway analysis module supports pathway analysis (integrating enrichment analysis and pathway topology analysis) and visualization for 21 model organisms, including Human, Mouse, Rat, Cow, Chicken, Zebrafish, **Arabidopsis thaliana**, Rice, Drosophila, Malaria, **S. cerevisae**, **E.coli**, and others, with a total of ~1600 metabolic pathways.

## 2. Pathway Analysis Example Workflow

In this workflow, we will perform pathway analysis where the input is a list of compound names.

```{r}
# Create vector consisting of compounds for enrichment analysis 
tmp.vec <- c("Acetoacetic acid", "Beta-Alanine", "Creatine", "Dimethylglycine", "Fumaric acid", "Glycine", "Homocysteine", "L-Cysteine", "L-Isolucine", "L-Phenylalanine", "L-Serine", "L-Threonine", "L-Tyrosine", "L-Valine", "Phenylpyruvic acid", "Propionic acid", "Pyruvic acid", "Sarcosine")

# Create mSetObj for storing objects created during your analysis
mSet<-InitDataObjects("conc", "pathora", FALSE)

# Set up mSetObj with the list of compounds
mSet<-Setup.MapData(mSet, tmp.vec);

# Cross reference list of compounds against libraries (hmdb, pubchem, chebi, kegg, metlin)
mSet<-CrossReferencing(mSet, "name");

mSet<-CreateMappingResultTable(mSet);

# Perform matching against compound w. out matches
mSet<-PerformDetailMatch(mSet, "L-Isolucine");

# Get list of candidates for matching
mSet<-GetCandidateList(mSet);

# Replace selected compound
mSet<-SetCandidate(mSet, "L-Isolucine", "L-Isoleucine");

# Select the pathway library, ranging from mammals to prokaryotes
mSet<-SetKEGG.PathLib(mSet, "hsa")

# Set the metabolite filter
mSet<-SetMetabolomeFilter(mSet, F);

# Calculate the over representation analysis score, here we selected to use the hypergeometric test (alternative is Fisher's exact test)
# A results table "pathway_results.csv" will be created and found within your working directory
mSet<-CalculateOraScore(mSet, "rbc", "hyperg")

# Plot of the Pathway Analysis Overview 
mSet<-PlotPathSummary(mSet, "path_view_0_", "png", 72, width=NA)

# Plot a specific metabolic pathway, in this case "Glycine, serine and threonine metabolism"
mSet<-PlotMetPath(mSet, "Glycine, serine and threonine metabolism", 480, 420)

```

## 3. Sweave Report

Following analysis, a comprehensive report can be generated which contains a detailed description of each step performed in the R package, embedded with graphical and tabular outputs. To prepare the sweave report, please use the *PreparePDFReport* function. You must ensure that you have the nexessary Latex libraries to generate the report (i.e. pdflatex, LaTexiT). The object created *must* be named *mSet*, and specify the user name in quotation marks. 
